#!/usr/bin/env python3
"""Build the Harms pages from the Welfare Footprint Project report.

Reads the chapter PDFs in data/report/, finds every page that mentions each
harm, renders those pages as images into docs/report/<chapter>/pNN.webp and
writes docs/report.js (a manifest of chapters and, for each harm, the pages
that mention it) plus a small stub page docs/harms/<slug>.html per harm.

Usage:  python3 scripts/build_harms.py            (needs: pip install pymupdf pillow)
"""
import io, json, os, re, sys
import pymupdf
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF_DIR = os.path.join(ROOT, 'data', 'report')
OUT_IMG = os.path.join(ROOT, 'docs', 'report')
OUT_STUB = os.path.join(ROOT, 'docs', 'harms')
ZOOM, QUALITY = 1.4, 72          # about 100 dpi; roughly 60-120 KB per page

# The book: Schuck-Paim C & Alonso WJ (eds), Quantifying Pain in Broiler Chickens, Welfare Footprint Project, 2022.
CHAPTERS = [
    ('01-introduction',   1, 'Introduction'),
    ('02-lameness',       2, 'Lameness'),
    ('03-cardiopulmonary', 3, 'Cardiopulmonary challenges'),
    ('04-thermal-stress', 4, 'Thermal stress'),
    ('05-behavior',       5, 'Behavioral deprivation'),
    ('06-breeders',       6, 'Breeders'),
    ('07-main-findings',  7, 'Main findings'),
    ('08-stunning',       8, 'Stunning and slaughter'),
]

# Harm name (must match the names in docs/text.js and docs/wfp.js) -> patterns a page must match (all of them).
HARMS = [
    ('Lameness',                 [r'\blame(?:ness)?\b|gait scor|leg (?:health|disorder|problem|weakness)']),
    ('Ascites',                  [r'ascites|pulmonary hypertension']),
    ('Sudden death syndrome',    [r'sudden death|\bSDS\b']),
    ('Heat stress',              [r'heat[- ]stress|thermal stress|hyperthermia|heat stroke']),
    ('No foraging or exploring', [r'foraging|exploration|exploratory']),
    ('No perching',              [r'\bperch|\broost']),
    ('No dustbathing',           [r'dust[- ]?bath']),
    ('Breeder hen hunger',       [r'breeder', r'hunger|feed[- ]restrict']),
    ('Breeder hen peritonitis',  [r'peritonitis']),
    ('Stunning and slaughter',   [r'\bstun|shackl|waterbath|controlled[- ]atmosphere']),
]

def slug(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')

def is_reference_page(text):
    """A page that is mostly a numbered reference list."""
    return len(re.findall(r'^\s*\d{1,3}\.\s', text, re.M)) >= 6

def main():
    manifest = {'book': {'title': 'Quantifying Pain in Broiler Chickens', 'authors': 'Schuck-Paim C & Alonso WJ (eds)',
                         'publisher': 'Welfare Footprint Project', 'year': 2022, 'url': 'https://welfarefootprint.org/broilers'},
                'chapters': [], 'harms': {}}
    docs = {}
    for cslug, num, title in CHAPTERS:
        path = os.path.join(PDF_DIR, cslug + '.pdf')
        if not os.path.exists(path):
            print('missing', path); continue
        docs[cslug] = pymupdf.open(path)
        manifest['chapters'].append({'slug': cslug, 'number': num, 'title': title, 'pages': docs[cslug].page_count})

    # Which pages mention which harm
    needed = set()
    for name, patterns in HARMS:
        hits = []
        for cslug, num, title in CHAPTERS:
            if cslug not in docs: continue
            for i, page in enumerate(docs[cslug]):
                text = page.get_text()
                if is_reference_page(text): continue
                if all(re.search(p, text, re.I) for p in patterns):
                    hits.append([cslug, i + 1]); needed.add((cslug, i + 1))
        manifest['harms'][name] = {'slug': slug(name), 'pages': hits}
        print('%-26s %3d pages' % (name, len(hits)))

    # Render the pages that are needed (skip ones already rendered)
    total = 0
    for cslug, n in sorted(needed):
        d = os.path.join(OUT_IMG, cslug); os.makedirs(d, exist_ok=True)
        f = os.path.join(d, 'p%02d.webp' % n)
        if not os.path.exists(f):
            pix = docs[cslug][n - 1].get_pixmap(matrix=pymupdf.Matrix(ZOOM, ZOOM))
            img = Image.frombytes('RGB', (pix.width, pix.height), pix.samples)
            img.save(f, 'WEBP', quality=QUALITY, method=6)
        total += os.path.getsize(f)
    # Remove rendered pages no longer needed
    for cslug in os.listdir(OUT_IMG) if os.path.isdir(OUT_IMG) else []:
        for fn in os.listdir(os.path.join(OUT_IMG, cslug)):
            m = re.match(r'p(\d+)\.webp$', fn)
            if m and (cslug, int(m.group(1))) not in needed:
                os.remove(os.path.join(OUT_IMG, cslug, fn))
    print('%d page images, %.1f MB' % (len(needed), total / 1e6))

    with open(os.path.join(ROOT, 'docs', 'report.js'), 'w') as out:
        out.write('// Generated by scripts/build_harms.py. Which pages of the Welfare Footprint Project report mention each harm.\n')
        out.write('var REPORT = ' + json.dumps(manifest, indent=1, ensure_ascii=False) + ';\n')

    os.makedirs(OUT_STUB, exist_ok=True)
    for name, _ in HARMS:
        with open(os.path.join(OUT_STUB, slug(name) + '.html'), 'w') as out:
            out.write(STUB.replace('{NAME}', name))
    print('wrote docs/report.js and %d stub pages in docs/harms/' % len(HARMS))

STUB = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{NAME}</title>
<link rel="stylesheet" href="../site.css">
<link rel="stylesheet" href="../harms.css">
</head>
<body data-page="harms" data-root="../">
<nav class="side" id="side"></nav>
<main id="harm"></main>
<script src="../text.js"></script>
<script src="../nav.js"></script>
<script src="../report.js"></script>
<script src="../harms.js"></script>
<script>renderHarmPage('{NAME}');</script>
</body>
</html>
"""

if __name__ == '__main__':
    main()
